const Controller = require("../controllers/controller")
const ProductController = require("../controllers/productController")
const BannerController = require("../controllers/bannerController")
const {authentication, authorization} = require("../middlewares/auth")
const errorHandler = require("../middlewares/errorHandler")
const router = require("express").Router()

router.post("/login", Controller.postLogin)
router.use(authentication)
router.post("/product", ProductController.postProduct)
router.post("/banner", BannerController.postBanner)
router.get("/products", ProductController.getProducts)
router.get("/categories", ProductController.getCategories)
router.get("/banners", BannerController.getBanners)
router.use(authorization)
router.put("/product/:id", ProductController.putProduct)
router.delete("/product/:id", ProductController.deleteProduct)
router.put("/banner/:id", BannerController.putBanner)
router.delete("/banner/:id", BannerController.deleteBanner)
router.use(errorHandler)

module.exports = router